apps/delivery/urls.py
#!/usr/bin/env python
# -*- coding=utf-8 -*-
__author__ = 'jimit'
__CreateAt__ = '2019\3\7 9:24'

"""lagou URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path,re_path
from .views import DeliveryRecuiterView,DeliveryApplierView,DeliveryView
app_name = 'delivery'

urlpatterns = [
    path('', DeliveryApplierView.as_view(), name="delivery_page"),
    path('recruiter/', DeliveryRecuiterView.as_view(), name="delivery_recruiter_page"),
    re_path('recruiter/(?P<user_id>\d+)', DeliveryView.as_view(), name="delivery_interview_page"),
]

apps/enterprice/urls.py
#!/usr/bin/env python
# -*- coding=utf-8 -*-
__author__ = 'jimit'
__CreateAt__ = '2019\3\7 9:24'

"""lagou URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path,re_path
from .views import CompanyView,CommentView,CompanyListView,CompanyDetailView

app_name="enterprice"

urlpatterns = [
    re_path('detail/(?P<enterprice_id>\d+)/', CompanyDetailView.as_view(), name="company_page"),
    path('', CompanyView.as_view(), name="company_info_page"),
    path('comments/', CommentView.as_view(), name="comment_page"),
    path('list/', CompanyListView.as_view(), name="company_list_page"),
]

apps/interview/urls.py
#!/usr/bin/env python
# -*- coding=utf-8 -*-
__author__ = 'jimit'
__CreateAt__ = '2019\3\7 9:24'

"""lagou URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path,re_path
from .views import MyInterviewView,InterviewCommentView,InterviewDetailView,InterviewRecordView,InterviewResultView,InterviewView,InvitationView

app_name="interview"

urlpatterns = [
    path('mine/', MyInterviewView.as_view(), name="myinterview_page"),
    re_path('(?P<resume_id>\d+)/', InterviewView.as_view(), name="interview_page"),
    path('invitations/', InvitationView.as_view(), name="invitation_page"),
    path('record/', InterviewRecordView.as_view(), name="interview_record_page"),
    path('detail/', InterviewDetailView.as_view(), name="interview_detail_page"),
    re_path('result/(?P<interview_id>\d+)', InterviewResultView.as_view(), name="interview_result_page"),
    path('comment/', InterviewCommentView.as_view(), name="interview_comment_page"),
]

apps/job/urls.py
#!/usr/bin/env python
# -*- coding=utf-8 -*-
__author__ = 'jimit'
__CreateAt__ = '2019\3\7 9:24'

"""lagou URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path,re_path
from .views import RecuiterView,PositionView,JobView,JobListView,JobCustomizeView

app_name="job"

urlpatterns = [
    path('recruiter/', RecuiterView.as_view(), name="recruiter_page"),
    path('search/', PositionView.as_view(), name="search_page"),
    re_path('detail/(?P<job_id>\d+)/', JobView.as_view(), name="job_page"),
    path('list/', JobListView.as_view(), name="job_list_page"),
    path('customize/', JobCustomizeView.as_view(), name="job_customize_page"),
]

apps/offer/urls.py
#!/usr/bin/env python
# -*- coding=utf-8 -*-
__author__ = 'jimit'
__CreateAt__ = '2019\3\7 9:24'

"""lagou URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path,re_path
from .views import OfferDetailView,OfferView

app_name ="offer"

urlpatterns = [
    re_path('(?P<interview_id>\d+)/', OfferView.as_view(), name="offer_page"),
    path('detail/', OfferDetailView.as_view(), name="offer_detail_page"),
]

apps/resume/urls.py
#!/usr/bin/env python
# -*- coding=utf-8 -*-
__author__ = 'jimit'
__CreateAt__ = '2019\3\7 9:24'

"""lagou URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path,re_path
from .views import ResumDetailView,ResumeListView,ResumeCollectionView,ResumeView

app_name = 'resume'

urlpatterns = [
    path('', ResumeView.as_view(), name="resume_page"),
    re_path('detail/(?P<resume_id>\d+)/', ResumDetailView.as_view(), name="resume_detail_page"),
    path('list/', ResumeListView.as_view(), name="resume_list_page"),
    path('collection/', ResumeCollectionView.as_view(), name="resume_collection_page"),
]

apps/user/urls.py
#!/usr/bin/env python
# -*- coding=utf-8 -*-
__author__ = 'jimit'
__CreateAt__ = '2019\3\7 9:24'

"""lagou URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path,include
from .views import UserView,PofileView,LagouView,LoginView,RegisterView,LogoutView,RoleView

app_name = 'user'

urlpatterns = [
    path('login/', LoginView.as_view(), name="login_page"),
    path('register/', RegisterView.as_view(), name="register_page"),
    path('profile/', PofileView.as_view(), name="profile_page"),
    path('logout/', LogoutView.as_view(), name="logout_page"),
    path('logout/', LogoutView.as_view(), name="logout_page"),
    path('role/', RoleView.as_view(), name="role_page"),
]

lagou/urls.py
from django.contrib import admin
from django.urls import path,include
from user.views import LagouView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('lagou/', LagouView.as_view(), name="lagou_page"),
    path('', LagouView.as_view(), name="lagou_page"),
    path("users/", include('user.urls', namespace="user")),
    path("offers/", include('offer.urls', namespace="offer")),
    path("resumes/", include('resume.urls', namespace="resume")),
    path("deliveries/", include('delivery.urls', namespace="delivery")),
    path("collections/", include('collection.urls', namespace="collection")),
    path("interviews/", include('interview.urls', namespace="interview")),
    path("jobs/", include('job.urls', namespace="job")),
    path("enterprices/", include('enterprice.urls', namespace="enterprice")),
]

apps/collection/models.py
from django.db import models
from db.base_model import BaseModel
from user.models import User
from job.models import Position
from enterprice.models import EnterPrice
# Create your models here.
class Collection(BaseModel):
    collection_enum=(
        ('WX','无效'),
        ('YX','有效')
    )
    id = models.AutoField('收藏ID',primary_key=True)
    user = models.ForeignKey(User,verbose_name='用户',on_delete=models.CASCADE)
    position = models.ForeignKey(Position,verbose_name = '职位',on_delete=models.CASCADE)
    enterprice = models.ForeignKey(EnterPrice,verbose_name = '企业',on_delete=models.CASCADE)
    is_valid=models.CharField('收藏状态',choices=collection_enum,max_length=2)

    class Meta:
        verbose_name = '收藏'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.enterprice,self.position

apps/job/models.py
from django.db import models
from db.base_model import BaseModel
from tinymce.models import HTMLField
from enterprice.models import EnterPrice
# Create your models here.
class Position(BaseModel):
    id = models.AutoField('职位ID',primary_key=True)
    name = models.CharField('职称',max_length=64)
    city = models.CharField('工作城市',max_length=64)
    position_type = models.CharField('职位类型',max_length=5)
    experience_required = models.CharField('工作经验要求',max_length=10)
    degree_required = models.CharField('最低学历要求',max_length=5)
    salary = models.CharField('工资范围',max_length=10)
    attractive_desc=models.TextField('职位诱惑',null=True,blank=True)
    position_desc = HTMLField('职位描述',null=True,blank=True)
    effect_days = models.CharField('岗位有效期',default="一周",max_length=6)
    position_status=models.CharField('职位状态',max_length=2,default='有效')
    enterprice = models.ForeignKey(EnterPrice,verbose_name="企业",on_delete=models.CASCADE)

    class Meta:
        verbose_name = '职位'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

apps/offer/models.py
from django.db import models
from db.base_model import BaseModel
from job.models import Position
from enterprice.models import EnterPrice
# Create your models here.
class Offer(BaseModel):
    offer_enum=(
        ('WX','无效'),
        ('YX','有效'),
        ('WJ', '婉拒'),
        ('AC', '接受')
    )
    id = models.AutoField('OfferID',primary_key=True)
    position = models.ForeignKey(Position,verbose_name = '职位',on_delete=models.CASCADE)
    enterprice = models.ForeignKey(EnterPrice,verbose_name = '企业',on_delete=models.CASCADE)
    salary = models.CharField('薪资待遇',max_length=32)
    offer_desc = models.TextField('offer描述')
    offer_status=models.CharField('offer状态',choices=offer_enum,max_length=2,default='WX')

    class Meta:
        verbose_name = 'Offer'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.enterprice,self.position,self.salary,self.offer_status

apps/resume/models.py
from django.db import models
from db.base_model import BaseModel
from user.models import User

# Create your models here.
class Resume(BaseModel):
    id = models.AutoField('简历ID',primary_key=True)
    name = models.CharField('昵称', max_length=50, default='')
    creer_time = models.IntegerField('工作年限', default=0)
    gender = models.CharField('性别', max_length=10,default='male')
    age = models.IntegerField('年龄',null=True,blank=True)
    city = models.CharField('城市', max_length=20, null=True, blank=True)
    mobile = models.CharField('手机',max_length=20)
    email = models.EmailField('邮箱地址',max_length=30)
    school = models.CharField('毕业院校',max_length=64)
    degree = models.CharField('最高学历',max_length=10,default="本科")
    major = models.CharField('专业',max_length=64)
    self_desc = models.TextField('自我描述')
    lastest_job_desc = models.TextField('最近一份工作描述')
    lastest_job_position = models.TextField('最近一份工作职称')
    desire_position = models.CharField('期望职位',max_length=32)
    job_type = models.CharField('工作性质',max_length=2,default='全职')
    desire_monthly_salary = models.CharField('期望月薪',max_length=16,null=True,blank=True)
    desire_city = models.CharField('期望城市',max_length=32,null=True,blank=True)
    current_status =models.CharField('当前状态',max_length=4,default='已离职')
    is_public = models.IntegerField('是否开启邀约',default=0)
    speciality = models.TextField('特长优势')
    user = models.ForeignKey(User,verbose_name='用户',on_delete=models.CASCADE)

    class Meta:
        verbose_name = '我的简历'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

apps/collection/views.py
from django.shortcuts import render,reverse,redirect
from django.views import View
from db.login_mixin import LoginRequiredMixin

# Create your views here.
class CollectionView(LoginRequiredMixin,View):
    '''收藏列表'''
    def get(self,request):
        if request.user.role.name == "recruiter":
            return redirect(reverse("resume:resume_collection_page"))
        return render(request, 'collections.html')

apps/job/views.py
from django.shortcuts import render
from django.views import View
from db.login_mixin import LoginRequiredMixin
from .models import Position
from enterprice.models import EnterPrice
# Create your views here.
class JobCustomizeView(LoginRequiredMixin,View):
    '''岗位订阅'''
    def get(self,request):
        return render(request, 'job_customize.html')

class JobListView(View):
    '''岗位列表'''
    def get(self,request):
        position_list = Position.objects.all()
        return render(request, 'index.html',{"position_list":position_list})

class JobView(View):
    '''工作详情页'''
    def get(self,request,job_id):
        job = Position.objects.get(id=job_id)
        return render(request, 'job.html',{"job":job})

class PositionView(View):
    '''岗位信息'''
    def get(self,request):
        return render(request, 'search.html')

class RecuiterView(LoginRequiredMixin,View):
    '''招聘需求页面'''
    def get(self,request):
        return render(request, 'recruiter.html')

    def post(self,request):
        name = request.POST.get("position","")
        city = request.POST.get("city", "")
        degree_required = request.POST.get("degree_required","")
        attractive_desc = request.POST.get("attractive_desc","")
        salary = request.POST.get("salary","")
        experience_required = request.POST.get("experience_required", "")
        position_type = request.POST.get("position_type", "")
        effect_days = request.POST.get("effect_days", "")
        position_desc = request.POST.get("position_desc","")
        if not all([name,city,degree_required,attractive_desc,salary,experience_required,position_type,effect_days,position_desc]):
            message="信息输入不完整"
            return render(request, "enterpriceinfo.html", {"message": message})
        else:
            print([name,city,degree_required,attractive_desc,salary,experience_required,position_type,effect_days,position_desc])
            position = Position()
            position.name = name
            position.city = city
            position.degree_required = degree_required
            position.attractive_desc = attractive_desc
            position.salary = salary
            position.experience_required = experience_required
            position.position_type = position_type
            position.effect_days = effect_days
            position.position_desc = position_desc
            position.enterprice_id = EnterPrice.objects.get(user_id=request.user.id,is_delete=0).id
            position.save()
            message = "招聘信息发布完成"
            return  render(request,"successful.html",{"message":message})

apps/offer/views.py
from django.shortcuts import render
from django.views import View
from db.login_mixin import LoginRequiredMixin
from interview.models import Interview

# Create your views here.

class OfferView(LoginRequiredMixin,View):
    '''Offer提交页面'''
    def get(self,request,interview_id):
        interview = Interview.objects.get(id=interview_id)
        resume = interview.user.resume_set.all()[0]
        return render(request, 'offer.html',{"interview":interview,"resume":resume})

class OfferDetailView(LoginRequiredMixin,View):
    '''招聘需求页面'''
    def get(self,request):
        return render(request, 'offer_detail.html')

templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="/static/css/normalize.css" rel="stylesheet">
    <link rel="Shortcut Icon" href="/static/images/favicon.ico">
</head>
<body>
<footer id="footer"><!--通用footer组件模板@author pooky@lagou.com-->
    <div data-name="职位" data-index="0" data-type="custom" class="footer-tab-custom">
        <a href="{% url 'job:job_list_page' %}"><span class="icon"></span>
            <span class="text">职位</span></a>
    </div>
    <div data-name="搜索" data-index="1" data-type="search" class="footer-tab-search selected">
        <a href="{% url 'job:search_page' %}">
            <span class="icon selected"></span>
            <span class="text">搜索</span>
        </a>
    </div>
    <div data-name="我的" data-index="2" data-type="mine" class="footer-tab-mine">
        <a href="{% url 'user:profile_page' %}">
            <span class="icon"></span>
            <span class="text">我的</span></a>
    </div>
</footer>
</body>
</html>

templates/footer_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="/static/css/normalize.css" rel="stylesheet">
    <link rel="Shortcut Icon" href="/static/images/favicon.ico">
</head>
<body>
<footer id="footer"><!--通用footer组件模板@author pooky@lagou.com-->
    <div data-name="企业" data-index="0" data-type="custom" class="footer-tab-custom">
        <a href="{% url 'enterprice:company_list_page' %}"><span class="icon"></span>
            <span class="text">企业</span></a>
    </div>
    <div data-name="搜索" data-index="1" data-type="search" class="footer-tab-search selected">
        <a href="{% url 'job:search_page' %}">
            <span class="icon selected"></span>
            <span class="text">搜索</span>
        </a>
    </div>
    <div data-name="我的" data-index="2" data-type="mine" class="footer-tab-mine">
        <a href="{% url 'user:profile_page' %}">
            <span class="icon"></span>
            <span class="text">我的</span></a>
    </div>
</footer>
</body>
</html>

templates/interview.html
<!DOCTYPE html>
<html data-dpr="1">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>拉勾网</title>
    <link rel="stylesheet" type="text/css" href="/static/css/main.html_aio_fecea31.css">
    <link href="/static/css/common.css" rel="stylesheet">
    <link rel="Shortcut Icon" href="/static/images/favicon.ico">
    <script charset="UTF-8"></script>
</head>
<body style="font-size: 12px;">
<header id="header">面试邀请函
    <div class="left"><a href="{% url "resume:resume_detail_page" resume.id %}"><span class="corner"></span></a></div>
</header>
<div class="container cleafix">
    <section class="form_container active" data-view="codeLogin">
        <header class="form_header"><h2>面试邀请</h2></header>
        <form class="form_body form_register" method="post" action="{% url "delivery:delivery_interview_page" resume.user_id %}">
            <div class="input_label phone_wrapper">
                <!--
	@require "mobile/modules/country-code/main.js"
	@require "mobile/modules/country-code/main.less"
-->
                <input type="text" name="applier" class="input_text_resume" value="{{ resume.name }}" readonly>
                 <select name="position" class="input_text_resume">
                     <option value=""><span class="hint_text">请选择岗位</span></option>
                    {% for item in position_list   %}
                        <option value="{{ item.id }}">{{ item.name }}</option>
                    {% endfor %} }}
                </select>
                <input type="text" name="invitation" placeholder="请输入面邀信息" class="input_text_resume">
            </div>
            <div class="input_label btn_group">
                <input type="submit" class="submit_btn" value="提交">
            </div>
        </form>
    </section>
</div>
<input type="hidden" id="verifyStyle" style="display: none" value="nolagou">
</body>
</html>

templates/interviews_record.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no, email=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <title>拉勾网</title>
    <meta content="拉勾,拉勾网,拉勾招聘,拉钩, 拉钩网 ,互联网招聘,拉勾互联网招聘, 移动互联网招聘, 垂直互联网招聘, 微信招聘, 微博招聘, 拉勾官网, 拉勾百科,跳槽, 高薪职位, 互联网圈子, IT招聘, 职场招聘, 猎头招聘,O2O招聘, LBS招聘, 社交招聘, 校园招聘, 校招,社会招聘,社招"
          name="keywords">
    <meta content="拉勾网是3W旗下的互联网领域垂直招聘网站" name="description">
    <link href="/static/css/normalize.css" rel="stylesheet">
    <link href="/static/css/common.css" rel="stylesheet">
    <link rel="Shortcut Icon" href="/static/images/favicon.ico">
    <link href="/static/css/interview.css" rel="stylesheet">
    <link href="/static/css/collectlist.css" rel="stylesheet">
</head>

<body ontouchstart="">

<header id="header">面试记录
    <div class="left"><a href="{% url "user:profile_page" %}"><span class="corner"></span></a></div>
</header>

<div id="content">
    <div class="tab">
        <a href="#" id="btn_inted" class="tab-item selected" onclick="showInterviewed()">已面试</a><a href="#" id="btn_will_inter" class="tab-item" onclick="showWillInterview()">将面试</a>
    </div>
    <ul class="list " id="interviewed" style="display: block">
        {% for item in interview_ym_list %}
            <a href="{% url "interview:interview_result_page" item.id %}">
                <li class="activeable item" data-index="0">
                <img src="{{ item.user.image }}" class="item-logo">
            <div class="item-desc">
                <div class="desc-left">
                {% for resume in resume_list %}
                    {% if item.user_id == resume.user_id %}
                    <h2 class="item-title">{{ resume.name }}</h2>
                    {% endif %}
                {% endfor %}
                    <p class="item-info">
                            <span class="item-pos">
                                面试岗位：{{ item.position.name }}
                            </span>
                            <span class="item-pos">
                                期望薪资： {% for resume in resume_list %}
                                {% if item.user_id == resume.user_id %}
                                    {{ resume.desire_monthly_salary }} {{ resume.desire_city }}
                                {% endif %}
                                {% endfor %}
                            </span>
                    </p>
                </div>
                <div class="desc-right">
                    <div class="experience">
                         <span>
                            结果：{% if item.interview_status == "YM" %}待定{% endif %}
                        </span>
                        <p class="item-time">{{ item.update_time }}</p>
                    </div>
                </div>
            </div>
            </li></a>{% endfor %}
    </ul>
     <ul class="list " id="will_interview" style="display: none">
          {% for item in interview_jm_list %}
            <a href="{% url "interview:interview_result_page" item.id%}">
                <li class="activeable item" data-index="0">
                <img src="{{ item.user.image }}" class="item-logo">
            <div class="item-desc">
                <div class="desc-left">
                    {% for resume in resume_list %}
                    {% if item.user_id == resume.user_id %}
                    <h2 class="item-title">{{ resume.name }}</h2>
                    {% endif %}
                    {% endfor %}
                    <p class="item-info">
                            <span class="item-pos">
                                面试岗位：{{ item.position.name }}
                            </span>
                            <span class="item-pos">
                                期望薪资： {% for resume in resume_list %}
                                {% if item.user_id == resume.user_id %}
                                    {{ resume.desire_monthly_salary }} {{ resume.desire_city }}
                                {% endif %}
                                {% endfor %}
                            </span>
                    </p>
                </div>
                <div class="desc-right">
                    <div class="experience">
                         <span>
                            结果：{% if item.interview_status == "JM" %}未结束{% endif %}
                        </span>
                        <p class="item-time">{{ item.update_time }}</p>
                    </div>
                </div>
            </div>
            </li></a>
     {% endfor %}
        </ul>
    <ul class="list" id="empty" style="display: none">
        <li class="list-empty">
            暂时没有将面试的记录，去<a href="{% url "job:job_list_page" %}">投简历</a>吧
        </li>
    </ul>

</div>
<!-- dep -->

<!---数据为空-->
<script id="tpl-list-empty" type="text/html">

    <li class="list-empty">
        暂时没有将面试的记录，去<a href={% url "job:job_list_page" %}>投简历</a>吧
    </li>
</script>


<div id="dialog-base-container-6" class="dialog-base-container" style="display: none;">
    <div class="dialog-masker"></div>
    <div class="dialog-wrapper" style="width:84.375%;">
        <div class="dialog-content"><span class="dialog-close-new"></span>
            <div class="dialog-confirm">是否确认已收到offer？</div>
            <div class="dialog-buttons">
                <div class="dialog-innerbtns"><span class="dialog-btn dialog-btn-green"
                                                    dialog-btn-inx="0">确认已收到</span><span
                        class="dialog-btn dialog-btn-last" dialog-btn-inx="1">目前未收到</span></div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function showInterviewed() {
        document.getElementById("interviewed").style.display="block";
        document.getElementById("will_interview").style.display="none";
        document.getElementById("empty").style.display="none";
        document.getElementById("btn_inted").className="tab-item selected";
        document.getElementById("btn_will_inter").className="tab-item";
    }
    function showWillInterview() {
        document.getElementById("interviewed").style.display="none";
        document.getElementById("will_interview").style.display="block";
        document.getElementById("empty").style.display="none";
        document.getElementById("btn_inted").className="tab-item";
        document.getElementById("btn_will_inter").className="tab-item selected";
    }
</script>
</body>
{% include "footer.html" %}
</html>